# Generated by Django 6.1 on 2026-08-14 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('peso_actual', models.DecimalField(decimal_places=2, help_text='Peso en kg', max_digits=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacuna', 'Vacuna'), ('desparasitante', 'Desparasitante')], max_length=20)),
                ('nombre_medicamento', models.CharField(max_length=100)),
                ('fecha_aplicacion', models.DateField()),
                ('proxima_fecha', models.DateField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.mascota')),
            ],
        ),
    ]
