# Generated by Django 6.1 on 2026-08-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromedico',
            name='tipo_desparasitante',
            field=models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo'), ('ambos', 'Ambos'), ('no_aplica', 'No aplica (Es vacuna)')], default='no_aplica', max_length=20),
        ),
        migrations.AddField(
            model_name='registromedico',
            name='vacuna',
            field=models.CharField(choices=[('rabia', 'Rabia'), ('sextuple', 'Séxtuple'), ('kc', 'KC (Tos de Perrera)'), ('otra', 'Otra'), ('no_aplica', 'No aplica (Es desparasitante)')], default='no_aplica', max_length=50),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(choices=[('mestiza', 'Mestiza'), ('schnauzer', 'Schnauzer'), ('golden_retriever', 'Golden Retriever'), ('poodle', 'Poodle'), ('bulldog', 'Bulldog'), ('pug', 'Pug'), ('pastor_aleman', 'Pastor Alemán'), ('otra', 'Otra')], default='mestiza', max_length=100),
        ),
        migrations.AlterField(
            model_name='registromedico',
            name='nombre_medicamento',
            field=models.CharField(blank=True, help_text='Ej: Nexgard, Bravecto. (Opcional)', max_length=100, null=True),
        ),
    ]
